// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: claros_common_form_formtemplate_type.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace claros.protogen.common.form
{

    [global::ProtoBuf.ProtoContract()]
    public enum FormTemplateType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"FT_UNKNOWN")]
        FtUnknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"FT_PLANT")]
        FtPlant = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"FT_LABORATORY")]
        FtLaboratory = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"FT_ENTERPRISE")]
        FtEnterprise = 3,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
