// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: claros_common_core_auditevent_type.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace claros.protogen.common.core
{

    [global::ProtoBuf.ProtoContract()]
    public enum AuditEventType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"AE_UNKNOWN")]
        AeUnknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"AE_CREATE")]
        AeCreate = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"AE_READ")]
        AeRead = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"AE_UPDATE")]
        AeUpdate = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"AE_DELETE")]
        AeDelete = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"AE_SENT")]
        AeSent = 5,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
