// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: claros_instrument_measurement_definition.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace claros.protogen.instrument
{

    [global::ProtoBuf.ProtoContract()]
    public partial class InstrumentMeasurementDefinition : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string instrumentMeasurementId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string fusionId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string locationId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        public uint parameterId { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public uint displayUnitId { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public bool isVisible { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public SCSensorBinding scSensorBinding
        {
            get { return __pbn__binding.Is(8) ? ((SCSensorBinding)__pbn__binding.Object) : default; }
            set { __pbn__binding = new global::ProtoBuf.DiscriminatedUnionObject(8, value); }
        }
        public bool ShouldSerializescSensorBinding() => __pbn__binding.Is(8);
        public void ResetscSensorBinding() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__binding, 8);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__binding;

        [global::ProtoBuf.ProtoMember(9)]
        public MilliAmpBinding milliAmpBinding
        {
            get { return __pbn__binding.Is(9) ? ((MilliAmpBinding)__pbn__binding.Object) : default; }
            set { __pbn__binding = new global::ProtoBuf.DiscriminatedUnionObject(9, value); }
        }
        public bool ShouldSerializemilliAmpBinding() => __pbn__binding.Is(9);
        public void ResetmilliAmpBinding() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__binding, 9);

        [global::ProtoBuf.ProtoMember(10, Name = @"limits")]
        public global::System.Collections.Generic.List<global::claros.protogen.common.core.Limit> Limits { get; } = new global::System.Collections.Generic.List<global::claros.protogen.common.core.Limit>();

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue("")]
        public string createdById { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12)]
        public global::claros.protogen.common.core.ClarosDateTime createdOn { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        [global::System.ComponentModel.DefaultValue("")]
        public string modifiedById { get; set; } = "";

        [global::ProtoBuf.ProtoMember(14)]
        public global::claros.protogen.common.core.ClarosDateTime modifiedOn { get; set; }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
