// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: claros_operations_spreadsheet_worksheet_type.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace claros.protogen.operations.spreadsheet
{

    [global::ProtoBuf.ProtoContract()]
    public enum WorksheetType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"W_UNKNOWN")]
        WUnknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"W_FIFTEEN_MINUTE")]
        WFifteenMinute = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"W_FOUR_HOUR")]
        WFourHour = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"W_DAILY")]
        WDaily = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"W_MONTHLY")]
        WMonthly = 4,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
