// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: claros_common_form_formfield_definition.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace claros.protogen.common.form
{

    [global::ProtoBuf.ProtoContract()]
    public partial class FormFieldDefinition : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"guid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Guid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public FormDataEntryType formDataEntryType { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public bool isDataEntryTypeLocked { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"column")]
        public FormFieldWorksheetColumnUTC Column
        {
            get { return __pbn__fieldDefinition.Is(5) ? ((FormFieldWorksheetColumnUTC)__pbn__fieldDefinition.Object) : default; }
            set { __pbn__fieldDefinition = new global::ProtoBuf.DiscriminatedUnionObject(5, value); }
        }
        public bool ShouldSerializeColumn() => __pbn__fieldDefinition.Is(5);
        public void ResetColumn() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__fieldDefinition, 5);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__fieldDefinition;

        [global::ProtoBuf.ProtoMember(6)]
        public FormFieldTextRepeated textRepeated
        {
            get { return __pbn__fieldDefinition.Is(6) ? ((FormFieldTextRepeated)__pbn__fieldDefinition.Object) : default; }
            set { __pbn__fieldDefinition = new global::ProtoBuf.DiscriminatedUnionObject(6, value); }
        }
        public bool ShouldSerializetextRepeated() => __pbn__fieldDefinition.Is(6);
        public void ResettextRepeated() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__fieldDefinition, 6);

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
