// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: claros_common_core_reportablequalifierdefinition_type.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace claros.protogen.common.core
{

    [global::ProtoBuf.ProtoContract()]
    public enum ReportableQualifierDefinitionType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"RQD_UNKNOWN")]
        RqdUnknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"RQD_ENTEREDVALUE")]
        RqdEnteredvalue = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"RQD_ZERO")]
        RqdZero = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"RQD_HALFENTERED")]
        RqdHalfentered = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"RQD_CONSTANT")]
        RqdConstant = 4,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
