// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: claros_common_core_dayofweek.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace claros.protogen.common.core
{

    [global::ProtoBuf.ProtoContract()]
    public enum DayOfWeek
    {
        [global::ProtoBuf.ProtoEnum(Name = @"DOW_UNKNOWN")]
        DowUnknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"DOW_SUNDAY")]
        DowSunday = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"DOW_MONDAY")]
        DowMonday = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"DOW_TUESDAY")]
        DowTuesday = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"DOW_WEDNESDAY")]
        DowWednesday = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"DOW_THURSDAY")]
        DowThursday = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"DOW_FRIDAY")]
        DowFriday = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"DOW_SATURDAY")]
        DowSaturday = 7,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
