// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: claros_instrument_event.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace claros.protogen.instrument
{

    [global::ProtoBuf.ProtoContract()]
    public partial class InstrumentEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"calibrations")]
        public global::System.Collections.Generic.List<Calibration> Calibrations { get; } = new global::System.Collections.Generic.List<Calibration>();

        [global::ProtoBuf.ProtoMember(2, Name = @"errors")]
        public global::System.Collections.Generic.List<EventMetaData> Errors { get; } = new global::System.Collections.Generic.List<EventMetaData>();

        [global::ProtoBuf.ProtoMember(3, Name = @"info")]
        public global::System.Collections.Generic.List<EventMetaData> Infoes { get; } = new global::System.Collections.Generic.List<EventMetaData>();

        [global::ProtoBuf.ProtoMember(4, Name = @"limits")]
        public global::System.Collections.Generic.List<EventMetaData> Limits { get; } = new global::System.Collections.Generic.List<EventMetaData>();

        [global::ProtoBuf.ProtoMember(5, Name = @"reminders")]
        public global::System.Collections.Generic.List<EventMetaData> Reminders { get; } = new global::System.Collections.Generic.List<EventMetaData>();

        [global::ProtoBuf.ProtoMember(6, Name = @"warnings")]
        public global::System.Collections.Generic.List<EventMetaData> Warnings { get; } = new global::System.Collections.Generic.List<EventMetaData>();

        [global::ProtoBuf.ProtoMember(7, Name = @"prognosys")]
        public global::System.Collections.Generic.List<PrognosysData> Prognosys { get; } = new global::System.Collections.Generic.List<PrognosysData>();

        [global::ProtoBuf.ProtoMember(8)]
        public global::claros.protogen.common.core.ClarosDateTime eventDateTime { get; set; }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
