// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: claros_common_core_recurrence_type.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace claros.protogen.common.core
{

    [global::ProtoBuf.ProtoContract()]
    public enum RecurrenceType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"R_UNKNOWN")]
        RUnknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"R_FIFTEENMINUTE")]
        RFifteenminute = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"R_HOURLY")]
        RHourly = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"R_FOURHOUR")]
        RFourhour = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"R_DAILY")]
        RDaily = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"R_WEEKLY")]
        RWeekly = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"R_DAYSOFWEEK")]
        RDaysofweek = 6,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
