// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: claros_common_core_limit_type.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace claros.protogen.common.core
{

    [global::ProtoBuf.ProtoContract()]
    public enum LimitType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"L_UNKNOWN")]
        LUnknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"L_HIGHALARM")]
        LHighalarm = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"L_HIGHNEAR")]
        LHighnear = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"L_LOWNEAR")]
        LLownear = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"L_LOWALARM")]
        LLowalarm = 4,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
