// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: claros_operations_spreadsheet_worksheet_definition.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace claros.protogen.operations.spreadsheet
{

    [global::ProtoBuf.ProtoContract()]
    public partial class WorksheetDefinition : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"version")]
        public uint Version { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint startRow { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint endRow { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"columns")]
        public global::System.Collections.Generic.List<Column> Columns { get; } = new global::System.Collections.Generic.List<Column>();

        [global::ProtoBuf.ProtoMember(99)]
        public global::claros.protogen.common.core.AuditEvent auditEvent { get; set; }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
