// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: claros_common_core_recurrence.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace claros.protogen.common.core
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Recurrence : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public RecurrenceType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ClarosDateTime startDate { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint minuteOffset { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"daysOfWeek", IsPacked = true)]
        public global::System.Collections.Generic.List<DayOfWeek> daysOfWeeks { get; } = new global::System.Collections.Generic.List<DayOfWeek>();

        [global::ProtoBuf.ProtoMember(5, Name = @"duration")]
        public uint Duration { get; set; }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
