// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: claros_operations_spreadsheet_worksheet_column.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace claros.protogen.operations.spreadsheet
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Column : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint columnNumber { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public uint parameterId { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public uint displayUnitId { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string locationId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        public bool isActive { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"limits")]
        public global::System.Collections.Generic.List<global::claros.protogen.common.core.Limit> Limits { get; } = new global::System.Collections.Generic.List<global::claros.protogen.common.core.Limit>();

        [global::ProtoBuf.ProtoMember(9)]
        public global::claros.protogen.common.core.DataSourceType dataSourceType { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public global::claros.protogen.instrument.InstrumentMeasurementBinding instrumentMeasurementBinding
        {
            get { return __pbn__binding.Is(10) ? ((global::claros.protogen.instrument.InstrumentMeasurementBinding)__pbn__binding.Object) : default; }
            set { __pbn__binding = new global::ProtoBuf.DiscriminatedUnionObject(10, value); }
        }
        public bool ShouldSerializeinstrumentMeasurementBinding() => __pbn__binding.Is(10);
        public void ResetinstrumentMeasurementBinding() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__binding, 10);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__binding;

        [global::ProtoBuf.ProtoMember(11)]
        public global::claros.protogen.common.computation.ComputationBinding computationBinding
        {
            get { return __pbn__binding.Is(11) ? ((global::claros.protogen.common.computation.ComputationBinding)__pbn__binding.Object) : default; }
            set { __pbn__binding = new global::ProtoBuf.DiscriminatedUnionObject(11, value); }
        }
        public bool ShouldSerializecomputationBinding() => __pbn__binding.Is(11);
        public void ResetcomputationBinding() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__binding, 11);

        [global::ProtoBuf.ProtoMember(12, Name = @"reportableQualiferDefinition")]
        public global::System.Collections.Generic.List<global::claros.protogen.common.core.ReportableQualifierDefinition> reportableQualiferDefinitions { get; } = new global::System.Collections.Generic.List<global::claros.protogen.common.core.ReportableQualifierDefinition>();

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
