// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: claros_common_core_dayofweek.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace claros.protoc.Common.Core {

  /// <summary>Holder for reflection information generated from claros_common_core_dayofweek.proto</summary>
  public static partial class ClarosCommonCoreDayofweekReflection {

    #region Descriptor
    /// <summary>File descriptor for claros_common_core_dayofweek.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClarosCommonCoreDayofweekReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJjbGFyb3NfY29tbW9uX2NvcmVfZGF5b2Z3ZWVrLnByb3RvEhJjbGFyb3Mu",
            "Y29tbW9uLmNvcmUqlAEKCURheU9mV2VlaxIPCgtET1dfVU5LTk9XThAAEg4K",
            "CkRPV19TVU5EQVkQARIOCgpET1dfTU9OREFZEAISDwoLRE9XX1RVRVNEQVkQ",
            "AxIRCg1ET1dfV0VETkVTREFZEAQSEAoMRE9XX1RIVVJTREFZEAUSDgoKRE9X",
            "X0ZSSURBWRAGEhAKDERPV19TQVRVUkRBWRAHYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::claros.protoc.Common.Core.DayOfWeek), }, null));
    }
    #endregion

  }
  #region Enums
  public enum DayOfWeek {
    [pbr::OriginalName("DOW_UNKNOWN")] DowUnknown = 0,
    [pbr::OriginalName("DOW_SUNDAY")] DowSunday = 1,
    [pbr::OriginalName("DOW_MONDAY")] DowMonday = 2,
    [pbr::OriginalName("DOW_TUESDAY")] DowTuesday = 3,
    [pbr::OriginalName("DOW_WEDNESDAY")] DowWednesday = 4,
    [pbr::OriginalName("DOW_THURSDAY")] DowThursday = 5,
    [pbr::OriginalName("DOW_FRIDAY")] DowFriday = 6,
    [pbr::OriginalName("DOW_SATURDAY")] DowSaturday = 7,
  }

  #endregion

}

#endregion Designer generated code
