// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: claros_common_core_reportablequalifier.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace claros.protoc.Common.Core {

  /// <summary>Holder for reflection information generated from claros_common_core_reportablequalifier.proto</summary>
  public static partial class ClarosCommonCoreReportablequalifierReflection {

    #region Descriptor
    /// <summary>File descriptor for claros_common_core_reportablequalifier.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClarosCommonCoreReportablequalifierReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CixjbGFyb3NfY29tbW9uX2NvcmVfcmVwb3J0YWJsZXF1YWxpZmllci5wcm90",
            "bxISY2xhcm9zLmNvbW1vbi5jb3JlGjFjbGFyb3NfY29tbW9uX2NvcmVfcmVw",
            "b3J0YWJsZXF1YWxpZmllcl90eXBlLnByb3RvInsKE1JlcG9ydGFibGVRdWFs",
            "aWZpZXISTAoXcmVwb3J0YWJsZVF1YWxpZmllclR5cGUYASABKA4yKy5jbGFy",
            "b3MuY29tbW9uLmNvcmUuUmVwb3J0YWJsZVF1YWxpZmllclR5cGUSFgoOcXVh",
            "bGlmaWVkVmFsdWUYAiABKAliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::claros.protoc.Common.Core.ClarosCommonCoreReportablequalifierTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::claros.protoc.Common.Core.ReportableQualifier), global::claros.protoc.Common.Core.ReportableQualifier.Parser, new[]{ "ReportableQualifierType", "QualifiedValue" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ReportableQualifier : pb::IMessage<ReportableQualifier> {
    private static readonly pb::MessageParser<ReportableQualifier> _parser = new pb::MessageParser<ReportableQualifier>(() => new ReportableQualifier());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReportableQualifier> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::claros.protoc.Common.Core.ClarosCommonCoreReportablequalifierReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReportableQualifier() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReportableQualifier(ReportableQualifier other) : this() {
      reportableQualifierType_ = other.reportableQualifierType_;
      qualifiedValue_ = other.qualifiedValue_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReportableQualifier Clone() {
      return new ReportableQualifier(this);
    }

    /// <summary>Field number for the "reportableQualifierType" field.</summary>
    public const int ReportableQualifierTypeFieldNumber = 1;
    private global::claros.protoc.Common.Core.ReportableQualifierType reportableQualifierType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::claros.protoc.Common.Core.ReportableQualifierType ReportableQualifierType {
      get { return reportableQualifierType_; }
      set {
        reportableQualifierType_ = value;
      }
    }

    /// <summary>Field number for the "qualifiedValue" field.</summary>
    public const int QualifiedValueFieldNumber = 2;
    private string qualifiedValue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string QualifiedValue {
      get { return qualifiedValue_; }
      set {
        qualifiedValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReportableQualifier);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReportableQualifier other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ReportableQualifierType != other.ReportableQualifierType) return false;
      if (QualifiedValue != other.QualifiedValue) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ReportableQualifierType != 0) hash ^= ReportableQualifierType.GetHashCode();
      if (QualifiedValue.Length != 0) hash ^= QualifiedValue.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ReportableQualifierType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ReportableQualifierType);
      }
      if (QualifiedValue.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(QualifiedValue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ReportableQualifierType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ReportableQualifierType);
      }
      if (QualifiedValue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(QualifiedValue);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReportableQualifier other) {
      if (other == null) {
        return;
      }
      if (other.ReportableQualifierType != 0) {
        ReportableQualifierType = other.ReportableQualifierType;
      }
      if (other.QualifiedValue.Length != 0) {
        QualifiedValue = other.QualifiedValue;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ReportableQualifierType = (global::claros.protoc.Common.Core.ReportableQualifierType) input.ReadEnum();
            break;
          }
          case 18: {
            QualifiedValue = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
