// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: claros_common_configuration_entity_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace claros.protoc.Common.Configuration {

  /// <summary>Holder for reflection information generated from claros_common_configuration_entity_type.proto</summary>
  public static partial class ClarosCommonConfigurationEntityTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for claros_common_configuration_entity_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClarosCommonConfigurationEntityTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1jbGFyb3NfY29tbW9uX2NvbmZpZ3VyYXRpb25fZW50aXR5X3R5cGUucHJv",
            "dG8SG2NsYXJvcy5jb21tb24uY29uZmlndXJhdGlvbioxCgpFbnRpdHlUeXBl",
            "Eg4KCkVUX1VOS05PV04QABITCg9FVF9GT1JNVEVNUExBVEUQAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::claros.protoc.Common.Configuration.EntityType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum EntityType {
    [pbr::OriginalName("ET_UNKNOWN")] EtUnknown = 0,
    [pbr::OriginalName("ET_FORMTEMPLATE")] EtFormtemplate = 1,
  }

  #endregion

}

#endregion Designer generated code
