// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: claros_operations_spreadsheet_spreadsheet.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace claros.protoc.Operations.Spreadsheet {

  /// <summary>Holder for reflection information generated from claros_operations_spreadsheet_spreadsheet.proto</summary>
  public static partial class ClarosOperationsSpreadsheetSpreadsheetReflection {

    #region Descriptor
    /// <summary>File descriptor for claros_operations_spreadsheet_spreadsheet.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClarosOperationsSpreadsheetSpreadsheetReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci9jbGFyb3Nfb3BlcmF0aW9uc19zcHJlYWRzaGVldF9zcHJlYWRzaGVldC5w",
            "cm90bxIdY2xhcm9zLm9wZXJhdGlvbnMuc3ByZWFkc2hlZXQaOmNsYXJvc19v",
            "cGVyYXRpb25zX3NwcmVhZHNoZWV0X3NwcmVhZHNoZWV0X2RlZmluaXRpb24u",
            "cHJvdG8aLWNsYXJvc19vcGVyYXRpb25zX3NwcmVhZHNoZWV0X3dvcmtzaGVl",
            "dC5wcm90byK6AQoLU3ByZWFkc2hlZXQSDAoEbmFtZRgBIAEoCRISCgpsb2Nh",
            "dGlvbklkGAIgASgJEkwKDnRpbWVEZWZpbml0aW9uGAMgAygLMjQuY2xhcm9z",
            "Lm9wZXJhdGlvbnMuc3ByZWFkc2hlZXQuU3ByZWFkc2hlZXREZWZpbml0aW9u",
            "EjsKCXdvcmtzaGVldBgEIAMoCzIoLmNsYXJvcy5vcGVyYXRpb25zLnNwcmVh",
            "ZHNoZWV0LldvcmtzaGVldGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::claros.protoc.Operations.Spreadsheet.ClarosOperationsSpreadsheetSpreadsheetDefinitionReflection.Descriptor, global::claros.protoc.Operations.Spreadsheet.ClarosOperationsSpreadsheetWorksheetReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::claros.protoc.Operations.Spreadsheet.Spreadsheet), global::claros.protoc.Operations.Spreadsheet.Spreadsheet.Parser, new[]{ "Name", "LocationId", "TimeDefinition", "Worksheet" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Spreadsheet : pb::IMessage<Spreadsheet> {
    private static readonly pb::MessageParser<Spreadsheet> _parser = new pb::MessageParser<Spreadsheet>(() => new Spreadsheet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Spreadsheet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::claros.protoc.Operations.Spreadsheet.ClarosOperationsSpreadsheetSpreadsheetReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Spreadsheet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Spreadsheet(Spreadsheet other) : this() {
      name_ = other.name_;
      locationId_ = other.locationId_;
      timeDefinition_ = other.timeDefinition_.Clone();
      worksheet_ = other.worksheet_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Spreadsheet Clone() {
      return new Spreadsheet(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// header
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "locationId" field.</summary>
    public const int LocationIdFieldNumber = 2;
    private string locationId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LocationId {
      get { return locationId_; }
      set {
        locationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timeDefinition" field.</summary>
    public const int TimeDefinitionFieldNumber = 3;
    private static readonly pb::FieldCodec<global::claros.protoc.Operations.Spreadsheet.SpreadsheetDefinition> _repeated_timeDefinition_codec
        = pb::FieldCodec.ForMessage(26, global::claros.protoc.Operations.Spreadsheet.SpreadsheetDefinition.Parser);
    private readonly pbc::RepeatedField<global::claros.protoc.Operations.Spreadsheet.SpreadsheetDefinition> timeDefinition_ = new pbc::RepeatedField<global::claros.protoc.Operations.Spreadsheet.SpreadsheetDefinition>();
    /// <summary>
    /// definition 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::claros.protoc.Operations.Spreadsheet.SpreadsheetDefinition> TimeDefinition {
      get { return timeDefinition_; }
    }

    /// <summary>Field number for the "worksheet" field.</summary>
    public const int WorksheetFieldNumber = 4;
    private static readonly pb::FieldCodec<global::claros.protoc.Operations.Spreadsheet.Worksheet> _repeated_worksheet_codec
        = pb::FieldCodec.ForMessage(34, global::claros.protoc.Operations.Spreadsheet.Worksheet.Parser);
    private readonly pbc::RepeatedField<global::claros.protoc.Operations.Spreadsheet.Worksheet> worksheet_ = new pbc::RepeatedField<global::claros.protoc.Operations.Spreadsheet.Worksheet>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::claros.protoc.Operations.Spreadsheet.Worksheet> Worksheet {
      get { return worksheet_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Spreadsheet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Spreadsheet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (LocationId != other.LocationId) return false;
      if(!timeDefinition_.Equals(other.timeDefinition_)) return false;
      if(!worksheet_.Equals(other.worksheet_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (LocationId.Length != 0) hash ^= LocationId.GetHashCode();
      hash ^= timeDefinition_.GetHashCode();
      hash ^= worksheet_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (LocationId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LocationId);
      }
      timeDefinition_.WriteTo(output, _repeated_timeDefinition_codec);
      worksheet_.WriteTo(output, _repeated_worksheet_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (LocationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LocationId);
      }
      size += timeDefinition_.CalculateSize(_repeated_timeDefinition_codec);
      size += worksheet_.CalculateSize(_repeated_worksheet_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Spreadsheet other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.LocationId.Length != 0) {
        LocationId = other.LocationId;
      }
      timeDefinition_.Add(other.timeDefinition_);
      worksheet_.Add(other.worksheet_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            LocationId = input.ReadString();
            break;
          }
          case 26: {
            timeDefinition_.AddEntriesFrom(input, _repeated_timeDefinition_codec);
            break;
          }
          case 34: {
            worksheet_.AddEntriesFrom(input, _repeated_worksheet_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
