// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: claros_common_form_formfield_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace claros.protoc.Common.Form {

  /// <summary>Holder for reflection information generated from claros_common_form_formfield_data.proto</summary>
  public static partial class ClarosCommonFormFormfieldDataReflection {

    #region Descriptor
    /// <summary>File descriptor for claros_common_form_formfield_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClarosCommonFormFormfieldDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CidjbGFyb3NfY29tbW9uX2Zvcm1fZm9ybWZpZWxkX2RhdGEucHJvdG8SEmNs",
            "YXJvcy5jb21tb24uZm9ybRoyY2xhcm9zX29wZXJhdGlvbnNfc3ByZWFkc2hl",
            "ZXRfd29ya3NoZWV0X2NlbGwucHJvdG8aHGNsYXJvc19pbnN0cnVtZW50X2Rh",
            "dGEucHJvdG8aI2NsYXJvc19jb21tb25fY29yZV9hdWRpdGV2ZW50LnByb3Rv",
            "IscBCg1Gb3JtRmllbGREYXRhEjMKBGNlbGwYASABKAsyIy5jbGFyb3Mub3Bl",
            "cmF0aW9ucy5zcHJlYWRzaGVldC5DZWxsSAASOQoOaW5zdHJ1bWVudERhdGEY",
            "AiABKAsyIS5jbGFyb3MuaW5zdHJ1bWVudC5JbnN0cnVtZW50RGF0YRIyCgph",
            "dWRpdEV2ZW50GGMgASgLMh4uY2xhcm9zLmNvbW1vbi5jb3JlLkF1ZGl0RXZl",
            "bnRCEgoQZmllbGREYXRhQmluZGluZ2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::claros.protoc.Operations.Spreadsheet.ClarosOperationsSpreadsheetWorksheetCellReflection.Descriptor, global::claros.protoc.Instrument.ClarosInstrumentDataReflection.Descriptor, global::claros.protoc.Common.Core.ClarosCommonCoreAuditeventReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::claros.protoc.Common.Form.FormFieldData), global::claros.protoc.Common.Form.FormFieldData.Parser, new[]{ "Cell", "InstrumentData", "AuditEvent" }, new[]{ "FieldDataBinding" }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class FormFieldData : pb::IMessage<FormFieldData> {
    private static readonly pb::MessageParser<FormFieldData> _parser = new pb::MessageParser<FormFieldData>(() => new FormFieldData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FormFieldData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::claros.protoc.Common.Form.ClarosCommonFormFormfieldDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FormFieldData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FormFieldData(FormFieldData other) : this() {
      instrumentData_ = other.instrumentData_ != null ? other.instrumentData_.Clone() : null;
      auditEvent_ = other.auditEvent_ != null ? other.auditEvent_.Clone() : null;
      switch (other.FieldDataBindingCase) {
        case FieldDataBindingOneofCase.Cell:
          Cell = other.Cell.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FormFieldData Clone() {
      return new FormFieldData(this);
    }

    /// <summary>Field number for the "cell" field.</summary>
    public const int CellFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::claros.protoc.Operations.Spreadsheet.Cell Cell {
      get { return fieldDataBindingCase_ == FieldDataBindingOneofCase.Cell ? (global::claros.protoc.Operations.Spreadsheet.Cell) fieldDataBinding_ : null; }
      set {
        fieldDataBinding_ = value;
        fieldDataBindingCase_ = value == null ? FieldDataBindingOneofCase.None : FieldDataBindingOneofCase.Cell;
      }
    }

    /// <summary>Field number for the "instrumentData" field.</summary>
    public const int InstrumentDataFieldNumber = 2;
    private global::claros.protoc.Instrument.InstrumentData instrumentData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::claros.protoc.Instrument.InstrumentData InstrumentData {
      get { return instrumentData_; }
      set {
        instrumentData_ = value;
      }
    }

    /// <summary>Field number for the "auditEvent" field.</summary>
    public const int AuditEventFieldNumber = 99;
    private global::claros.protoc.Common.Core.AuditEvent auditEvent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::claros.protoc.Common.Core.AuditEvent AuditEvent {
      get { return auditEvent_; }
      set {
        auditEvent_ = value;
      }
    }

    private object fieldDataBinding_;
    /// <summary>Enum of possible cases for the "fieldDataBinding" oneof.</summary>
    public enum FieldDataBindingOneofCase {
      None = 0,
      Cell = 1,
    }
    private FieldDataBindingOneofCase fieldDataBindingCase_ = FieldDataBindingOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FieldDataBindingOneofCase FieldDataBindingCase {
      get { return fieldDataBindingCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearFieldDataBinding() {
      fieldDataBindingCase_ = FieldDataBindingOneofCase.None;
      fieldDataBinding_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FormFieldData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FormFieldData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Cell, other.Cell)) return false;
      if (!object.Equals(InstrumentData, other.InstrumentData)) return false;
      if (!object.Equals(AuditEvent, other.AuditEvent)) return false;
      if (FieldDataBindingCase != other.FieldDataBindingCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (fieldDataBindingCase_ == FieldDataBindingOneofCase.Cell) hash ^= Cell.GetHashCode();
      if (instrumentData_ != null) hash ^= InstrumentData.GetHashCode();
      if (auditEvent_ != null) hash ^= AuditEvent.GetHashCode();
      hash ^= (int) fieldDataBindingCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (fieldDataBindingCase_ == FieldDataBindingOneofCase.Cell) {
        output.WriteRawTag(10);
        output.WriteMessage(Cell);
      }
      if (instrumentData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(InstrumentData);
      }
      if (auditEvent_ != null) {
        output.WriteRawTag(154, 6);
        output.WriteMessage(AuditEvent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (fieldDataBindingCase_ == FieldDataBindingOneofCase.Cell) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Cell);
      }
      if (instrumentData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InstrumentData);
      }
      if (auditEvent_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AuditEvent);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FormFieldData other) {
      if (other == null) {
        return;
      }
      if (other.instrumentData_ != null) {
        if (instrumentData_ == null) {
          InstrumentData = new global::claros.protoc.Instrument.InstrumentData();
        }
        InstrumentData.MergeFrom(other.InstrumentData);
      }
      if (other.auditEvent_ != null) {
        if (auditEvent_ == null) {
          AuditEvent = new global::claros.protoc.Common.Core.AuditEvent();
        }
        AuditEvent.MergeFrom(other.AuditEvent);
      }
      switch (other.FieldDataBindingCase) {
        case FieldDataBindingOneofCase.Cell:
          if (Cell == null) {
            Cell = new global::claros.protoc.Operations.Spreadsheet.Cell();
          }
          Cell.MergeFrom(other.Cell);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::claros.protoc.Operations.Spreadsheet.Cell subBuilder = new global::claros.protoc.Operations.Spreadsheet.Cell();
            if (fieldDataBindingCase_ == FieldDataBindingOneofCase.Cell) {
              subBuilder.MergeFrom(Cell);
            }
            input.ReadMessage(subBuilder);
            Cell = subBuilder;
            break;
          }
          case 18: {
            if (instrumentData_ == null) {
              InstrumentData = new global::claros.protoc.Instrument.InstrumentData();
            }
            input.ReadMessage(InstrumentData);
            break;
          }
          case 794: {
            if (auditEvent_ == null) {
              AuditEvent = new global::claros.protoc.Common.Core.AuditEvent();
            }
            input.ReadMessage(AuditEvent);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
