// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: claros_common_core_datasource_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace claros.protoc.Common.Core {

  /// <summary>Holder for reflection information generated from claros_common_core_datasource_type.proto</summary>
  public static partial class ClarosCommonCoreDatasourceTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for claros_common_core_datasource_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClarosCommonCoreDatasourceTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CihjbGFyb3NfY29tbW9uX2NvcmVfZGF0YXNvdXJjZV90eXBlLnByb3RvEhJj",
            "bGFyb3MuY29tbW9uLmNvcmUqoQEKDkRhdGFTb3VyY2VUeXBlEg4KCkRTX1VO",
            "S05PV04QABILCgdEU19GT1JNEAESEgoORFNfQ09NUFVUQVRJT04QAhISCg5E",
            "U19TUFJFQURTSEVFVBADEhwKGERTX0lOU1RSVU1FTlRNRUFTVVJFTUVOVBAE",
            "Eg0KCURTX0lNUE9SVBAFEh0KGURTX1NQUkVBRFNIRUVUX0RFRklOSVRJT04Q",
            "BmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::claros.protoc.Common.Core.DataSourceType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum DataSourceType {
    [pbr::OriginalName("DS_UNKNOWN")] DsUnknown = 0,
    [pbr::OriginalName("DS_FORM")] DsForm = 1,
    [pbr::OriginalName("DS_COMPUTATION")] DsComputation = 2,
    [pbr::OriginalName("DS_SPREADSHEET")] DsSpreadsheet = 3,
    [pbr::OriginalName("DS_INSTRUMENTMEASUREMENT")] DsInstrumentmeasurement = 4,
    [pbr::OriginalName("DS_IMPORT")] DsImport = 5,
    [pbr::OriginalName("DS_SPREADSHEET_DEFINITION")] DsSpreadsheetDefinition = 6,
  }

  #endregion

}

#endregion Designer generated code
