// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: claros_common_form_formdataentry_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace claros.protoc.Common.Form {

  /// <summary>Holder for reflection information generated from claros_common_form_formdataentry_type.proto</summary>
  public static partial class ClarosCommonFormFormdataentryTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for claros_common_form_formdataentry_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClarosCommonFormFormdataentryTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CitjbGFyb3NfY29tbW9uX2Zvcm1fZm9ybWRhdGFlbnRyeV90eXBlLnByb3Rv",
            "EhJjbGFyb3MuY29tbW9uLmZvcm0qbgoRRm9ybURhdGFFbnRyeVR5cGUSDwoL",
            "RkRFX1VOS05PV04QABISCg5GREVfSU5TVFJVTUVOVBABEhEKDUZERV9UT1RB",
            "TElaRVIQAhITCg9GREVfQ09OU1VNUFRJT04QAxIMCghGREVfVEVYVBAEYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::claros.protoc.Common.Form.FormDataEntryType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum FormDataEntryType {
    [pbr::OriginalName("FDE_UNKNOWN")] FdeUnknown = 0,
    [pbr::OriginalName("FDE_INSTRUMENT")] FdeInstrument = 1,
    [pbr::OriginalName("FDE_TOTALIZER")] FdeTotalizer = 2,
    [pbr::OriginalName("FDE_CONSUMPTION")] FdeConsumption = 3,
    [pbr::OriginalName("FDE_TEXT")] FdeText = 4,
  }

  #endregion

}

#endregion Designer generated code
