// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: claros_common_core_auditevent_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace claros.protoc.Common.Core {

  /// <summary>Holder for reflection information generated from claros_common_core_auditevent_type.proto</summary>
  public static partial class ClarosCommonCoreAuditeventTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for claros_common_core_auditevent_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClarosCommonCoreAuditeventTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CihjbGFyb3NfY29tbW9uX2NvcmVfYXVkaXRldmVudF90eXBlLnByb3RvEhJj",
            "bGFyb3MuY29tbW9uLmNvcmUqZwoOQXVkaXRFdmVudFR5cGUSDgoKQUVfVU5L",
            "Tk9XThAAEg0KCUFFX0NSRUFURRABEgsKB0FFX1JFQUQQAhINCglBRV9VUERB",
            "VEUQAxINCglBRV9ERUxFVEUQBBILCgdBRV9TRU5UEAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::claros.protoc.Common.Core.AuditEventType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum AuditEventType {
    [pbr::OriginalName("AE_UNKNOWN")] AeUnknown = 0,
    [pbr::OriginalName("AE_CREATE")] AeCreate = 1,
    [pbr::OriginalName("AE_READ")] AeRead = 2,
    [pbr::OriginalName("AE_UPDATE")] AeUpdate = 3,
    [pbr::OriginalName("AE_DELETE")] AeDelete = 4,
    [pbr::OriginalName("AE_SENT")] AeSent = 5,
  }

  #endregion

}

#endregion Designer generated code
