// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: claros_common_core_aggregate_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace claros.protoc.Common.Core {

  /// <summary>Holder for reflection information generated from claros_common_core_aggregate_type.proto</summary>
  public static partial class ClarosCommonCoreAggregateTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for claros_common_core_aggregate_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClarosCommonCoreAggregateTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CidjbGFyb3NfY29tbW9uX2NvcmVfYWdncmVnYXRlX3R5cGUucHJvdG8SEmNs",
            "YXJvcy5jb21tb24uY29yZSpLCg1BZ2dyZWdhdGVUeXBlEg0KCUFfVU5LTk9X",
            "ThAAEg0KCUFfTUlOSU1VTRABEg0KCUFfTUFYSU1VTRACEg0KCUFfQVZFUkFH",
            "RRADYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::claros.protoc.Common.Core.AggregateType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum AggregateType {
    [pbr::OriginalName("A_UNKNOWN")] AUnknown = 0,
    [pbr::OriginalName("A_MINIMUM")] AMinimum = 1,
    [pbr::OriginalName("A_MAXIMUM")] AMaximum = 2,
    [pbr::OriginalName("A_AVERAGE")] AAverage = 3,
  }

  #endregion

}

#endregion Designer generated code
