// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: claros_common_core_reportablequalifierdefinition_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace claros.protoc.Common.Core {

  /// <summary>Holder for reflection information generated from claros_common_core_reportablequalifierdefinition_type.proto</summary>
  public static partial class ClarosCommonCoreReportablequalifierdefinitionTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for claros_common_core_reportablequalifierdefinition_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClarosCommonCoreReportablequalifierdefinitionTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjtjbGFyb3NfY29tbW9uX2NvcmVfcmVwb3J0YWJsZXF1YWxpZmllcmRlZmlu",
            "aXRpb25fdHlwZS5wcm90bxISY2xhcm9zLmNvbW1vbi5jb3JlKn8KIVJlcG9y",
            "dGFibGVRdWFsaWZpZXJEZWZpbml0aW9uVHlwZRIPCgtSUURfVU5LTk9XThAA",
            "EhQKEFJRRF9FTlRFUkVEVkFMVUUQARIMCghSUURfWkVSTxACEhMKD1JRRF9I",
            "QUxGRU5URVJFRBADEhAKDFJRRF9DT05TVEFOVBAEYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::claros.protoc.Common.Core.ReportableQualifierDefinitionType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ReportableQualifierDefinitionType {
    [pbr::OriginalName("RQD_UNKNOWN")] RqdUnknown = 0,
    [pbr::OriginalName("RQD_ENTEREDVALUE")] RqdEnteredvalue = 1,
    [pbr::OriginalName("RQD_ZERO")] RqdZero = 2,
    [pbr::OriginalName("RQD_HALFENTERED")] RqdHalfentered = 3,
    [pbr::OriginalName("RQD_CONSTANT")] RqdConstant = 4,
  }

  #endregion

}

#endregion Designer generated code
