// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: claros_instrument_calibration_value.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace claros.protoc.Instrument {

  /// <summary>Holder for reflection information generated from claros_instrument_calibration_value.proto</summary>
  public static partial class ClarosInstrumentCalibrationValueReflection {

    #region Descriptor
    /// <summary>File descriptor for claros_instrument_calibration_value.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClarosInstrumentCalibrationValueReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiljbGFyb3NfaW5zdHJ1bWVudF9jYWxpYnJhdGlvbl92YWx1ZS5wcm90bxIR",
            "Y2xhcm9zLmluc3RydW1lbnQiRQoQQ2FsaWJyYXRpb25WYWx1ZRINCgV2YWx1",
            "ZRgBIAEoAhIMCgR1bml0GAIgASgNEhQKDGNoZW1pY2FsRm9ybRgDIAEoDWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::claros.protoc.Instrument.CalibrationValue), global::claros.protoc.Instrument.CalibrationValue.Parser, new[]{ "Value", "Unit", "ChemicalForm" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CalibrationValue : pb::IMessage<CalibrationValue> {
    private static readonly pb::MessageParser<CalibrationValue> _parser = new pb::MessageParser<CalibrationValue>(() => new CalibrationValue());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CalibrationValue> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::claros.protoc.Instrument.ClarosInstrumentCalibrationValueReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CalibrationValue() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CalibrationValue(CalibrationValue other) : this() {
      value_ = other.value_;
      unit_ = other.unit_;
      chemicalForm_ = other.chemicalForm_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CalibrationValue Clone() {
      return new CalibrationValue(this);
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 1;
    private float value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    /// <summary>Field number for the "unit" field.</summary>
    public const int UnitFieldNumber = 2;
    private uint unit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Unit {
      get { return unit_; }
      set {
        unit_ = value;
      }
    }

    /// <summary>Field number for the "chemicalForm" field.</summary>
    public const int ChemicalFormFieldNumber = 3;
    private uint chemicalForm_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ChemicalForm {
      get { return chemicalForm_; }
      set {
        chemicalForm_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CalibrationValue);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CalibrationValue other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Value, other.Value)) return false;
      if (Unit != other.Unit) return false;
      if (ChemicalForm != other.ChemicalForm) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Value != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Value);
      if (Unit != 0) hash ^= Unit.GetHashCode();
      if (ChemicalForm != 0) hash ^= ChemicalForm.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Value != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(Value);
      }
      if (Unit != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Unit);
      }
      if (ChemicalForm != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(ChemicalForm);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Value != 0F) {
        size += 1 + 4;
      }
      if (Unit != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unit);
      }
      if (ChemicalForm != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ChemicalForm);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CalibrationValue other) {
      if (other == null) {
        return;
      }
      if (other.Value != 0F) {
        Value = other.Value;
      }
      if (other.Unit != 0) {
        Unit = other.Unit;
      }
      if (other.ChemicalForm != 0) {
        ChemicalForm = other.ChemicalForm;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            Value = input.ReadFloat();
            break;
          }
          case 16: {
            Unit = input.ReadUInt32();
            break;
          }
          case 24: {
            ChemicalForm = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
