// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: claros_operations_spreadsheet_spreadsheet_definition.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace claros.protoc.Operations.Spreadsheet {

  /// <summary>Holder for reflection information generated from claros_operations_spreadsheet_spreadsheet_definition.proto</summary>
  public static partial class ClarosOperationsSpreadsheetSpreadsheetDefinitionReflection {

    #region Descriptor
    /// <summary>File descriptor for claros_operations_spreadsheet_spreadsheet_definition.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClarosOperationsSpreadsheetSpreadsheetDefinitionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjpjbGFyb3Nfb3BlcmF0aW9uc19zcHJlYWRzaGVldF9zcHJlYWRzaGVldF9k",
            "ZWZpbml0aW9uLnByb3RvEh1jbGFyb3Mub3BlcmF0aW9ucy5zcHJlYWRzaGVl",
            "dBojY2xhcm9zX2NvbW1vbl9jb3JlX3RpbWV3aW5kb3cucHJvdG8aIWNsYXJv",
            "c19jb21tb25fY29yZV90aW1lem9uZS5wcm90byKmAQoVU3ByZWFkc2hlZXRE",
            "ZWZpbml0aW9uEg8KB3ZlcnNpb24YASABKAkSMgoKdGltZXdpbmRvdxgCIAEo",
            "CzIeLmNsYXJvcy5jb21tb24uY29yZS5UaW1lV2luZG93Ei4KCHRpbWV6b25l",
            "GAMgASgOMhwuY2xhcm9zLmNvbW1vbi5jb3JlLlRpbWVab25lEhgKEHRpbWVX",
            "aW5kb3dPZmZzZXQYBCABKA1iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::claros.protoc.Common.Core.ClarosCommonCoreTimewindowReflection.Descriptor, global::claros.protoc.Common.Core.ClarosCommonCoreTimezoneReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::claros.protoc.Operations.Spreadsheet.SpreadsheetDefinition), global::claros.protoc.Operations.Spreadsheet.SpreadsheetDefinition.Parser, new[]{ "Version", "Timewindow", "Timezone", "TimeWindowOffset" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SpreadsheetDefinition : pb::IMessage<SpreadsheetDefinition> {
    private static readonly pb::MessageParser<SpreadsheetDefinition> _parser = new pb::MessageParser<SpreadsheetDefinition>(() => new SpreadsheetDefinition());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SpreadsheetDefinition> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::claros.protoc.Operations.Spreadsheet.ClarosOperationsSpreadsheetSpreadsheetDefinitionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpreadsheetDefinition() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpreadsheetDefinition(SpreadsheetDefinition other) : this() {
      version_ = other.version_;
      timewindow_ = other.timewindow_ != null ? other.timewindow_.Clone() : null;
      timezone_ = other.timezone_;
      timeWindowOffset_ = other.timeWindowOffset_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpreadsheetDefinition Clone() {
      return new SpreadsheetDefinition(this);
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 1;
    private string version_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Version {
      get { return version_; }
      set {
        version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timewindow" field.</summary>
    public const int TimewindowFieldNumber = 2;
    private global::claros.protoc.Common.Core.TimeWindow timewindow_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::claros.protoc.Common.Core.TimeWindow Timewindow {
      get { return timewindow_; }
      set {
        timewindow_ = value;
      }
    }

    /// <summary>Field number for the "timezone" field.</summary>
    public const int TimezoneFieldNumber = 3;
    private global::claros.protoc.Common.Core.TimeZone timezone_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::claros.protoc.Common.Core.TimeZone Timezone {
      get { return timezone_; }
      set {
        timezone_ = value;
      }
    }

    /// <summary>Field number for the "timeWindowOffset" field.</summary>
    public const int TimeWindowOffsetFieldNumber = 4;
    private uint timeWindowOffset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint TimeWindowOffset {
      get { return timeWindowOffset_; }
      set {
        timeWindowOffset_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SpreadsheetDefinition);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SpreadsheetDefinition other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Version != other.Version) return false;
      if (!object.Equals(Timewindow, other.Timewindow)) return false;
      if (Timezone != other.Timezone) return false;
      if (TimeWindowOffset != other.TimeWindowOffset) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Version.Length != 0) hash ^= Version.GetHashCode();
      if (timewindow_ != null) hash ^= Timewindow.GetHashCode();
      if (Timezone != 0) hash ^= Timezone.GetHashCode();
      if (TimeWindowOffset != 0) hash ^= TimeWindowOffset.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Version.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Version);
      }
      if (timewindow_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Timewindow);
      }
      if (Timezone != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Timezone);
      }
      if (TimeWindowOffset != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(TimeWindowOffset);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Version.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
      }
      if (timewindow_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timewindow);
      }
      if (Timezone != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Timezone);
      }
      if (TimeWindowOffset != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TimeWindowOffset);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SpreadsheetDefinition other) {
      if (other == null) {
        return;
      }
      if (other.Version.Length != 0) {
        Version = other.Version;
      }
      if (other.timewindow_ != null) {
        if (timewindow_ == null) {
          Timewindow = new global::claros.protoc.Common.Core.TimeWindow();
        }
        Timewindow.MergeFrom(other.Timewindow);
      }
      if (other.Timezone != 0) {
        Timezone = other.Timezone;
      }
      if (other.TimeWindowOffset != 0) {
        TimeWindowOffset = other.TimeWindowOffset;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Version = input.ReadString();
            break;
          }
          case 18: {
            if (timewindow_ == null) {
              Timewindow = new global::claros.protoc.Common.Core.TimeWindow();
            }
            input.ReadMessage(Timewindow);
            break;
          }
          case 24: {
            Timezone = (global::claros.protoc.Common.Core.TimeZone) input.ReadEnum();
            break;
          }
          case 32: {
            TimeWindowOffset = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
