// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: claros_common_core_timezone.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace claros.protoc.Common.Core {

  /// <summary>Holder for reflection information generated from claros_common_core_timezone.proto</summary>
  public static partial class ClarosCommonCoreTimezoneReflection {

    #region Descriptor
    /// <summary>File descriptor for claros_common_core_timezone.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClarosCommonCoreTimezoneReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFjbGFyb3NfY29tbW9uX2NvcmVfdGltZXpvbmUucHJvdG8SEmNsYXJvcy5j",
            "b21tb24uY29yZSomCghUaW1lWm9uZRIOCgpUWl9VTktOT1dOEAASCgoGVFpf",
            "VVRDEAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::claros.protoc.Common.Core.TimeZone), }, null));
    }
    #endregion

  }
  #region Enums
  public enum TimeZone {
    [pbr::OriginalName("TZ_UNKNOWN")] TzUnknown = 0,
    [pbr::OriginalName("TZ_UTC")] TzUtc = 1,
  }

  #endregion

}

#endregion Designer generated code
