// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: claros_operations_spreadsheet_worksheet.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace claros.protoc.Operations.Spreadsheet {

  /// <summary>Holder for reflection information generated from claros_operations_spreadsheet_worksheet.proto</summary>
  public static partial class ClarosOperationsSpreadsheetWorksheetReflection {

    #region Descriptor
    /// <summary>File descriptor for claros_operations_spreadsheet_worksheet.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClarosOperationsSpreadsheetWorksheetReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1jbGFyb3Nfb3BlcmF0aW9uc19zcHJlYWRzaGVldF93b3Jrc2hlZXQucHJv",
            "dG8SHWNsYXJvcy5vcGVyYXRpb25zLnNwcmVhZHNoZWV0GjJjbGFyb3Nfb3Bl",
            "cmF0aW9uc19zcHJlYWRzaGVldF93b3Jrc2hlZXRfdHlwZS5wcm90bxo4Y2xh",
            "cm9zX29wZXJhdGlvbnNfc3ByZWFkc2hlZXRfd29ya3NoZWV0X2RlZmluaXRp",
            "b24ucHJvdG8aMWNsYXJvc19vcGVyYXRpb25zX3NwcmVhZHNoZWV0X3dvcmtz",
            "aGVldF9yb3cucHJvdG8i1AEKCVdvcmtzaGVldBJDCg13b3Jrc2hlZXRUeXBl",
            "GAEgASgOMiwuY2xhcm9zLm9wZXJhdGlvbnMuc3ByZWFkc2hlZXQuV29ya3No",
            "ZWV0VHlwZRJQChR3b3Jrc2hlZXREZWZpbml0aW9ucxgCIAMoCzIyLmNsYXJv",
            "cy5vcGVyYXRpb25zLnNwcmVhZHNoZWV0LldvcmtzaGVldERlZmluaXRpb24S",
            "MAoEcm93cxgDIAMoCzIiLmNsYXJvcy5vcGVyYXRpb25zLnNwcmVhZHNoZWV0",
            "LlJvd2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::claros.protoc.Operations.Spreadsheet.ClarosOperationsSpreadsheetWorksheetTypeReflection.Descriptor, global::claros.protoc.Operations.Spreadsheet.ClarosOperationsSpreadsheetWorksheetDefinitionReflection.Descriptor, global::claros.protoc.Operations.Spreadsheet.ClarosOperationsSpreadsheetWorksheetRowReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::claros.protoc.Operations.Spreadsheet.Worksheet), global::claros.protoc.Operations.Spreadsheet.Worksheet.Parser, new[]{ "WorksheetType", "WorksheetDefinitions", "Rows" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Worksheet : pb::IMessage<Worksheet> {
    private static readonly pb::MessageParser<Worksheet> _parser = new pb::MessageParser<Worksheet>(() => new Worksheet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Worksheet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::claros.protoc.Operations.Spreadsheet.ClarosOperationsSpreadsheetWorksheetReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Worksheet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Worksheet(Worksheet other) : this() {
      worksheetType_ = other.worksheetType_;
      worksheetDefinitions_ = other.worksheetDefinitions_.Clone();
      rows_ = other.rows_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Worksheet Clone() {
      return new Worksheet(this);
    }

    /// <summary>Field number for the "worksheetType" field.</summary>
    public const int WorksheetTypeFieldNumber = 1;
    private global::claros.protoc.Operations.Spreadsheet.WorksheetType worksheetType_ = 0;
    /// <summary>
    /// header
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::claros.protoc.Operations.Spreadsheet.WorksheetType WorksheetType {
      get { return worksheetType_; }
      set {
        worksheetType_ = value;
      }
    }

    /// <summary>Field number for the "worksheetDefinitions" field.</summary>
    public const int WorksheetDefinitionsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::claros.protoc.Operations.Spreadsheet.WorksheetDefinition> _repeated_worksheetDefinitions_codec
        = pb::FieldCodec.ForMessage(18, global::claros.protoc.Operations.Spreadsheet.WorksheetDefinition.Parser);
    private readonly pbc::RepeatedField<global::claros.protoc.Operations.Spreadsheet.WorksheetDefinition> worksheetDefinitions_ = new pbc::RepeatedField<global::claros.protoc.Operations.Spreadsheet.WorksheetDefinition>();
    /// <summary>
    /// definition
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::claros.protoc.Operations.Spreadsheet.WorksheetDefinition> WorksheetDefinitions {
      get { return worksheetDefinitions_; }
    }

    /// <summary>Field number for the "rows" field.</summary>
    public const int RowsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::claros.protoc.Operations.Spreadsheet.Row> _repeated_rows_codec
        = pb::FieldCodec.ForMessage(26, global::claros.protoc.Operations.Spreadsheet.Row.Parser);
    private readonly pbc::RepeatedField<global::claros.protoc.Operations.Spreadsheet.Row> rows_ = new pbc::RepeatedField<global::claros.protoc.Operations.Spreadsheet.Row>();
    /// <summary>
    /// data
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::claros.protoc.Operations.Spreadsheet.Row> Rows {
      get { return rows_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Worksheet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Worksheet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (WorksheetType != other.WorksheetType) return false;
      if(!worksheetDefinitions_.Equals(other.worksheetDefinitions_)) return false;
      if(!rows_.Equals(other.rows_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (WorksheetType != 0) hash ^= WorksheetType.GetHashCode();
      hash ^= worksheetDefinitions_.GetHashCode();
      hash ^= rows_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (WorksheetType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) WorksheetType);
      }
      worksheetDefinitions_.WriteTo(output, _repeated_worksheetDefinitions_codec);
      rows_.WriteTo(output, _repeated_rows_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (WorksheetType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) WorksheetType);
      }
      size += worksheetDefinitions_.CalculateSize(_repeated_worksheetDefinitions_codec);
      size += rows_.CalculateSize(_repeated_rows_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Worksheet other) {
      if (other == null) {
        return;
      }
      if (other.WorksheetType != 0) {
        WorksheetType = other.WorksheetType;
      }
      worksheetDefinitions_.Add(other.worksheetDefinitions_);
      rows_.Add(other.rows_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            WorksheetType = (global::claros.protoc.Operations.Spreadsheet.WorksheetType) input.ReadEnum();
            break;
          }
          case 18: {
            worksheetDefinitions_.AddEntriesFrom(input, _repeated_worksheetDefinitions_codec);
            break;
          }
          case 26: {
            rows_.AddEntriesFrom(input, _repeated_rows_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
