name: Build main

on: 
  push:
    branches:
      - main

jobs:
  call-reusable-build:
    uses: ./.github/workflows/reusable-build.yml      
    with:
      publish: true
      release: true
    secrets: inherit
